language: cpp

before_script:
  - sudo apt-get update
  - sudo apt-get install libgecode-dev
  - wget -q https://sourceforge.net/projects/wxwindows/files/3.0.0/wxWidgets-3.0.0.tar.bz2
  - tar jxf wxWidgets-3.0.0.tar.bz2
  - cd ./wxWidgets-3.0.0
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig
  - cd ..

script:
  - make MokituSolver
